<p>
    Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolor laborum enim blanditiis, deserunt voluptate illo expedita vitae suscipit, cumque officiis delectus repellendus, earum unde aspernatur accusamus exercitationem nobis corporis repellat?
    Lorem ipsum dolor sit amet consectetur, adipisicing elit. Iure quibusdam earum voluptatem, porro repudiandae ea? Hic sunt quos quas impedit expedita voluptas, adipisci dicta veniam nulla! Magni dicta tempora rem. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestias odio, inventore distinctio voluptates suscipit dolorum ullam mollitia ut quasi unde magnam quam facilis explicabo eum quis corporis eveniet amet minima!
    Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolor laborum enim blanditiis, deserunt voluptate illo expedita vitae suscipit, cumque officiis delectus repellendus, earum unde aspernatur accusamus exercitationem nobis corporis repellat?
    Lorem ipsum dolor sit amet consectetur, adipisicing elit. Iure quibusdam earum voluptatem, porro repudiandae ea? Hic sunt quos quas impedit expedita voluptas, adipisci dicta veniam nulla! Magni dicta tempora rem. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestias odio, inventore distinctio voluptates suscipit dolorum ullam mollitia ut quasi unde magnam quam facilis explicabo eum quis corporis eveniet amet minima!
    Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolor laborum enim blanditiis, deserunt voluptate illo expedita vitae suscipit, cumque officiis delectus repellendus, earum unde aspernatur accusamus exercitationem nobis corporis repellat?
    Lorem ipsum dolor sit amet consectetur, adipisicing elit. Iure quibusdam earum voluptatem, porro repudiandae ea? Hic sunt quos quas impedit expedita voluptas, adipisci dicta veniam nulla! Magni dicta tempora rem. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestias odio, inventore distinctio voluptates suscipit dolorum ullam mollitia ut quasi unde magnam quam facilis explicabo eum quis corporis eveniet amet minima!
    Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolor laborum enim blanditiis, deserunt voluptate illo expedita vitae suscipit, cumque officiis delectus repellendus, earum unde aspernatur accusamus exercitationem nobis corporis repellat?
    Lorem ipsum dolor sit amet consectetur, adipisicing elit. Iure quibusdam earum voluptatem, porro repudiandae ea? Hic sunt quos quas impedit expedita voluptas, adipisci dicta veniam nulla! Magni dicta tempora rem. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestias odio, inventore distinctio voluptates suscipit dolorum ullam mollitia ut quasi unde magnam quam facilis explicabo eum quis corporis eveniet amet minima!
    Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolor laborum enim blanditiis, deserunt voluptate illo expedita vitae suscipit, cumque officiis delectus repellendus, earum unde aspernatur accusamus exercitationem nobis corporis repellat?
    Lorem ipsum dolor sit amet consectetur, adipisicing elit. Iure quibusdam earum voluptatem, porro repudiandae ea? Hic sunt quos quas impedit expedita voluptas, adipisci dicta veniam nulla! Magni dicta tempora rem. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestias odio, inventore distinctio voluptates suscipit dolorum ullam mollitia ut quasi unde magnam quam facilis explicabo eum quis corporis eveniet amet minima!
    Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolor laborum enim blanditiis, deserunt voluptate illo expedita vitae suscipit, cumque officiis delectus repellendus, earum unde aspernatur accusamus exercitationem nobis corporis repellat?
    Lorem ipsum dolor sit amet consectetur, adipisicing elit. Iure quibusdam earum voluptatem, porro repudiandae ea? Hic sunt quos quas impedit expedita voluptas, adipisci dicta veniam nulla! Magni dicta tempora rem. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestias odio, inventore distinctio voluptates suscipit dolorum ullam mollitia ut quasi unde magnam quam facilis explicabo eum quis corporis eveniet amet minima!
    Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolor laborum enim blanditiis, deserunt voluptate illo expedita vitae suscipit, cumque officiis delectus repellendus, earum unde aspernatur accusamus exercitationem nobis corporis repellat?
    Lorem ipsum dolor sit amet consectetur, adipisicing elit. Iure quibusdam earum voluptatem, porro repudiandae ea? Hic sunt quos quas impedit expedita voluptas, adipisci dicta veniam nulla! Magni dicta tempora rem. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestias odio, inventore distinctio voluptates suscipit dolorum ullam mollitia ut quasi unde magnam quam facilis explicabo eum quis corporis eveniet amet minima!
    Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolor laborum enim blanditiis, deserunt voluptate illo expedita vitae suscipit, cumque officiis delectus repellendus, earum unde aspernatur accusamus exercitationem nobis corporis repellat?
    Lorem ipsum dolor sit amet consectetur, adipisicing elit. Iure quibusdam earum voluptatem, porro repudiandae ea? Hic sunt quos quas impedit expedita voluptas, adipisci dicta veniam nulla! Magni dicta tempora rem. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestias odio, inventore distinctio voluptates suscipit dolorum ullam mollitia ut quasi unde magnam quam facilis explicabo eum quis corporis eveniet amet minima!
    Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolor laborum enim blanditiis, deserunt voluptate illo expedita vitae suscipit, cumque officiis delectus repellendus, earum unde aspernatur accusamus exercitationem nobis corporis repellat?
    Lorem ipsum dolor sit amet consectetur, adipisicing elit. Iure quibusdam earum voluptatem, porro repudiandae ea? Hic sunt quos quas impedit expedita voluptas, adipisci dicta veniam nulla! Magni dicta tempora rem. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestias odio, inventore distinctio voluptates suscipit dolorum ullam mollitia ut quasi unde magnam quam facilis explicabo eum quis corporis eveniet amet minima!
    Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolor laborum enim blanditiis, deserunt voluptate illo expedita vitae suscipit, cumque officiis delectus repellendus, earum unde aspernatur accusamus exercitationem nobis corporis repellat?
    Lorem ipsum dolor sit amet consectetur, adipisicing elit. Iure quibusdam earum voluptatem, porro repudiandae ea? Hic sunt quos quas impedit expedita voluptas, adipisci dicta veniam nulla! Magni dicta tempora rem. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestias odio, inventore distinctio voluptates suscipit dolorum ullam mollitia ut quasi unde magnam quam facilis explicabo eum quis corporis eveniet amet minima!
    Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolor laborum enim blanditiis, deserunt voluptate illo expedita vitae suscipit, cumque officiis delectus repellendus, earum unde aspernatur accusamus exercitationem nobis corporis repellat?
    Lorem ipsum dolor sit amet consectetur, adipisicing elit. Iure quibusdam earum voluptatem, porro repudiandae ea? Hic sunt quos quas impedit expedita voluptas, adipisci dicta veniam nulla! Magni dicta tempora rem. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestias odio, inventore distinctio voluptates suscipit dolorum ullam mollitia ut quasi unde magnam quam facilis explicabo eum quis corporis eveniet amet minima!

</p>

<style lang="sass">

p
    display: flex
    flex: 1
</style>